### ISSUE TITLE
Color Identity

### ISSUE THREAD

**Issue by ShawnieBoy** [lodici/magarena-cardbuilder#14]
Some form of color identity will be required for lands and other mana-producing permanents. Frame blending should display colors produced if amount <= 2

This can be obtained from .json

_Copied from original issue: magarena/magarenaCardBuilder#14_

**Comment by ShawnieBoy** [comment]
Color Identity cannot be determined by json.

Color for for cards with no mana cost are defined in the card script/definition and are already being matched. Only the addition of a color identity disc is required. (Check for mana cost, if null/0 and has color, add color identity)

A lands color identity would need to be determined by mana produced. Other mana-producers have their own identity separate from mana produced.

**Comment by ShawnieBoy** [comment]
I've noticed while looking at the ManaActivations for land, that pulling out the `.getManaTypes()` returns colorless for 'one mana of any color'. 
```java
final Collection<MagicManaActivation> landActivations = cardDef.getManaActivations();
if (landActivations.size() > 0) {
        for (MagicManaActivation activation:landActivations) {
            mana.addAll(activation.getManaTypes());
        }
        for (MagicManaType manaType:mana) {
            landColor.add(manaType.getColor());
        }
    }
```
Where is best to check for multicolor mana production?

**Comment by melvinzhang** [comment]
Look at ImageDrawingUtils.drawManaInfo

**Comment by ShawnieBoy** [comment]
Excellent - thanks.

**Comment by ShawnieBoy** [comment]
Implemented color piping for lands - Raises new Issues:

Dual color lands should return colorless banners, not gold.
Lands with mana production determined from land types not caught.
Lands which fetch other lands should have the color-match of the lands they can fetch.

**Comment by melvinzhang** [comment]
Note that basic land types are given their abilities in game as part of a whole game continuous effect. This is so that when a land becomes a basic land type, it gets the ability automatically.

**Comment by ShawnieBoy** [comment]
Yes, I think looking at the subtypes and checking for basic land types is the best way to go on that one. Possibly checking all card text in the case of fetch lands.

**Comment by ShawnieBoy** [comment]
Lands are all sorted:
![land1](https://cloud.githubusercontent.com/assets/2363180/7337695/075fb96e-ec2b-11e4-8534-f4e53e4c1968.png)
![land2](https://cloud.githubusercontent.com/assets/2363180/7337696/093b8c7c-ec2b-11e4-9ef9-830e4c05e982.png)
![land3](https://cloud.githubusercontent.com/assets/2363180/7337697/0b75a554-ec2b-11e4-8d0f-961d92680dac.png)
![land4](https://cloud.githubusercontent.com/assets/2363180/7337699/0d98f958-ec2b-11e4-892c-58aef49e048b.png)
