### ISSUE TITLE
Oracle Text requires line breaks

### ISSUE THREAD

**Issue by ShawnieBoy** [lodici/magarena-cardbuilder#2]
_From @ShawnieBoy on April 18, 2015 19:38_

ScriptBuilder is currently removing line breaks to allow the Card Explorer to display oracle without line-breaks.

CardBuilder will require these line-breaks for layout.

If Card Explorer can replace the line-breaks instead, this would allow for layout as per Oracle.

_Copied from original issue: magarena/magarenaCardBuilder#2_

**Comment by ShawnieBoy** [comment]
_From @lodici on April 18, 2015 20:6_

I think it would be better in the short term to try and avoid impacting Magarena. If further down the road it becomes a necessity in order to integrate CardBuilder then we can do that then.

However, I don't think there is anything stopping us updating ScriptsBuilder to include any info required by CardBuilder. So just add another property to the script file with the line breaks (eg ``cb.oracle=``). Same goes for any other data that would need to be added to a script in order for CardBuilder to work (eg. ``cb.frameLayout==``, etc). It should be easier now since I have refactored the messy constructor in CardData into separate methods calls. If it is necessary to hide the ``cb`` fields for scripts destined for Magarena then we can use something like ``-DcardBuilder=true`` to include/exclude those fields.

**Comment by ShawnieBoy** [comment]
Oh I wouldn't be doing anything that drastic - Just wanted to put something up on here to remember/consider. Keeping this well out of the way of Magarena.

Though saying that there's another part of me that's wondering about the reverse-engineering of the Magarena abilities back into text. Cards can gain and lose abilities so the oracle may not be the best place to get current card information during a game. (But enough of that).

I hadn't even considered a cardBuilder-ized run of the scriptBuilder. That will be very useful for testing things.

Pulling the framelayout etc. is certainly on the cards (ba-dum-tssh), however, just getting a basic format sorted first :grinning:

**Comment by ShawnieBoy** [comment]
Having an idea with the scriptbuilder replacing "\n" with our own defined line ending. This can be removed by the Card Explorer completely, and replaced back with a newline by the cardBuilder for rendering.

**Comment by melvinzhang** [comment]
we use ';' for ability separation in ability property, perhaps the same can be used for oracle text

**Comment by melvinzhang** [comment]
Darn, doesn't work. Some cards really do use ';' to separate abilities.

**Comment by melvinzhang** [comment]
I think your comment holds the answer, use "\n" itself. Eg
oracle=Flash\nFlying; fear\nWhen Dust Elemental enters the battlefield, return three creatures you control to their owner's hand.

**Comment by ShawnieBoy** [comment]
:+1:

**Comment by ShawnieBoy** [comment]
Works a treat with rendering, Card Explorer just needs to replace it with a space.

**Comment by lodici** [comment]
Try..
```
// in MagicCardDefinition
    public String getFlattenedText() {
        return this.text.replace("\n", " ");
    }
```
and
```
// in CardTableModel
#253            case 8:        return card.getFlattenedText();
```

**Comment by ShawnieBoy** [comment]
Looks good to me - Those last changes could be added to the main repository if I push the changes to scriptbuilder

**Comment by ShawnieBoy** [comment]
The "Choose one" cards look particularly good :grinning:

**Comment by lodici** [comment]
> Looks good to me - Those last changes could be added to the main repository if I push the changes to scriptbuilder

Go ahead and commit. My only slight concern is whether it will have any affect on performance of the Explorer since instead of displaying a static string it will now be performing 14,000+ ``replace`` string operations. I am sure it will be fine - worst case scenario is we can add a separate property to the script file.

**Comment by lodici** [comment]
No noticeable difference.

**Comment by melvinzhang** [comment]
might be better to probably convert the \n on loading the oracle property instead of when the text is needed, so text itself is with actual newlines inside instead of '\n'.

**Comment by melvinzhang** [comment]
Ignore that, just realized that \n is automatically converted to actual newlines in the string and what we're doing to removing them.

**Comment by lodici** [comment]
> No need to store two versions of the the text.

??? Just the ``text`` field containing the oracle text (now with ``\n``).

**Comment by ShawnieBoy** [comment]
Found an issue:

If a new line could fit in the line above , without over-running, it is being inserted instead. Need to look at the logic of text-flow in text box:

![text flow](https://cloud.githubusercontent.com/assets/2363180/7331777/42d9d246-eb17-11e4-9d53-69b2b7309724.png)

**Comment by ShawnieBoy** [comment]
Ok, fixed that - all that's needed now is a reparse of implemented script oracle text.

Pretty please @melvinzhang :heart_eyes:

**Comment by melvinzhang** [comment]
@ShawnieBoy  what do I need to do?

**Comment by ShawnieBoy** [comment]
Similar to the other line replacements in scripts you have done - With the updated scriptbuilder, replace the current oracle line in implemented scripts with the newly generated one.

I don't know how you manage to replace just one value, or I'd have done it :smile:

**Comment by melvinzhang** [comment]
I only have tools to update the value property. Anything else needs to be developed from scratch. Didn't you reparse the existing scripts to update the image property sometime back?

**Comment by melvinzhang** [comment]
If you can prepare a file in the following format:
oracle=[old text1][TAB]oracle=[new text1]
oracle=[old text2][TAB]oracle=[new text2]
I can help to perform the update.

**Comment by ShawnieBoy** [comment]
>I only have tools to update the value property, anything else needs to be developed. Didn't you reparse the existing scripts to update the image property sometime back?

I don't think so, I thought you did it...
Sorry, I thought you already had something that could do this. I'll see if I can come up with something.

**Comment by melvinzhang** [comment]
@ShawnieBoy I'm referring to 5131bca6f3b8a9 on the image property update. In case you missed it, I mentioned in the comment before yours that if you prepare a file with all the lines to be changed, I can do the update easily.

**Comment by ShawnieBoy** [comment]
>I'm referring to 5131bca on the image property update.
Wow - how did I do that? lol - I remember it happening but assumed you did it!

I think putting together the above file will probably take as much time as coming up with an alternative - I'll see if I can remember how I worked that refactor magic...

**Comment by melvinzhang** [comment]
If it helps, one file per card with only the new oracle line will do as
well. The filename should be that of the card script file.

**Comment by ShawnieBoy** [comment]
Ok, I think I can do that one - where shall I put the files?

**Comment by melvinzhang** [comment]
zip them and email to the mailing list

**Comment by ShawnieBoy** [comment]
Will do - just realised the list I was working with wasn't correct, just re-doing
