### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by lodici** [lodici/magarena-cardbuilder#20]
@ShawnieBoy I have refactored your code into separate classes which I have placed into ``magic.cardbuilder.renderers``. These now only use ``MagicCardDefinition`` - this means that missing cards work and there is a marked improvement in responsiveness (I am convinced that the unnecessary call to ``loadAbilities`` was the culprit). I have also re-instated the same functionality for ``setCard`` so images returned by the CardBuilder are cached and missing images are greyscaled. All your existing code remains untouched in ``magic.cardbuilder``.

**Comment by ShawnieBoy** [comment]
What about MagicCards? We can't send a MagicCardDefinition in it's place.

**Comment by lodici** [comment]
```
    public static BufferedImage getCardImage(final MagicCard card) {
        final MagicCardDefinition cardDef = card.getCardDefinition();
        final BufferedImage cardImage = CardFrame.getFrameType(cardDef);
        PTFrame.drawPTPanel(cardImage, cardDef);
        OracleText.drawOracleText(cardImage, cardDef);
        CardTitleFrame.drawCardName(cardImage, cardDef);
        CardTitleFrame.drawManaCost(cardImage, cardDef);
        CardTypeLine.drawCardTypeLine(cardImage, cardDef);
        return cardImage;
    }    
```

**Comment by ShawnieBoy** [comment]
Cool - not looked yet - Nice work :dancer:

**Comment by ShawnieBoy** [comment]
Whoops, supposed to be :grinning:  as in `:D`

**Comment by ShawnieBoy** [comment]
Still applies

**Comment by ShawnieBoy** [comment]
And as I expected - MagicCardDefinitions have no color (Was doing the same thing myself) - If you remove the greyscale you'll see

**Comment by lodici** [comment]
> And as I expected - MagicCardDefinitions have no color (Was doing the same thing myself) - If you remove the greyscale you'll see

You mean missing cards? Which are unplayable..

**Comment by ShawnieBoy** [comment]
Yes

**Comment by ShawnieBoy** [comment]
They all have the colorless frame

**Comment by lodici** [comment]
Then we probably need to look at the code for parsing missing scripts in that case.

**Comment by lodici** [comment]
Found the culprit in ``MagicCardDefinition``,,
```
    public boolean hasColor(final MagicColor color) {
        return (colorFlags&color.getMask())!=0 && !isMissing;
    }
```
Now just have to figure out why its there?

**Comment by melvinzhang** [comment]
"fix: color filter was including missing cards." --https://github.com/magarena/magarena/commit/1d076e729e4dd53915

**Comment by ShawnieBoy** [comment]
*chuckles*

**Comment by lodici** [comment]
Thanks @melvinzhang. Strange. I have no idea why I added that since you can use the status filter to remove the unplayable cards. I will get rid.

**Comment by ShawnieBoy** [comment]
I think it may have been before that filter was implemented

**Comment by melvinzhang** [comment]
getRarityString also has some strange handling for isMissing, perhaps worth a second look as well.

**Comment by lodici** [comment]
Beat me to it
```
    public String getRarityString() {
        return (isMissing || rarity == null ? "" : rarity.getName());
    }
```

**Comment by lodici** [comment]
The value in the Rarity column in the Explorer is suppressed if the card is missing. If that makes any sense?

**Comment by ShawnieBoy** [comment]
I'd say allow free searching of unimplemented cards - Can be annoying at times, when searching for cards to implement.

**Comment by melvinzhang** [comment]
In CardDefinitions.loadMissingCards, there is provision to support a very minimal MagicCardDefinition with only name. Is this still needed now we provide script files for all missing cards as part of the release?

**Comment by ShawnieBoy** [comment]
The only time I can see it coming up is during pre-release of a new set, where we have a list of cards, but no generated card scripts from mtgJson. Normally they're a bit behind us.

**Comment by melvinzhang** [comment]
As the gap period is typically one release, I propose we do not include cards with only names to keep things simple, MagicCardDefinition is constructed either from scripts or scripts_missing only.

**Comment by lodici** [comment]
> I'd say allow free searching of unimplemented cards - Can be annoying at times, when searching for cards to implement.

Do you mean using the "Search" filter?

**Comment by lodici** [comment]
> In CardDefinitions.loadMissingCards, there is provision to support a very minimal MagicCardDefinition with only name. Is this still needed now we provide script files for all missing cards as part of the release?

Possibly not now the background load has been implemented. It is related to the "Show missing card data" setting.

**Comment by ShawnieBoy** [comment]
>As the gap period is typically one release, I propose we do not include cards with only names to keep things simple, MagicCardDefinition is constructed either from scripts or scripts_missing only.

Sorry, I meant during our development, not when released

>Do you mean using the "Search" filter?

Well, all filters

For unimplemented cards you can't filter by type for example

**Comment by ShawnieBoy** [comment]
Subtype

**Comment by ShawnieBoy** [comment]
>For unimplemented cards you can't filter by type for example
I'm tired... Ignore me

**Comment by lodici** [comment]
> Subtype

Works for me.
