### ISSUE TITLE
Different/wrong card name font?

### ISSUE THREAD

**Issue by lodici** [lodici/magarena-cardbuilder#23]
Card name fonts look completely different.

![whispering madness](https://cloud.githubusercontent.com/assets/2443519/7299512/5019e7c4-e9ce-11e4-88ed-ade13b7a4cd4.jpg)
![screenshot00125](https://cloud.githubusercontent.com/assets/2443519/7299520/5b44481a-e9ce-11e4-9f41-47f0cbb9d532.png)

**Comment by ShawnieBoy** [comment]
The font for card names changed during/after M15 - anything prior uses a different font.

**Comment by ShawnieBoy** [comment]
![](http://magiccards.info/scans/en/m15/6.jpg)

![](http://magiccards.info/scans/en/m14/14.jpg)

**Comment by ShawnieBoy** [comment]
Looked more convincing flicking between the editions on [Magiccards.info](http://magiccards.info/m15/en/6.html), lol

**Comment by ShawnieBoy** [comment]
![](http://magiccards.info/scans/en/m15/83.jpg)

![](http://magiccards.info/scans/en/m14/78.jpg)

That's better

**Comment by lodici** [comment]
Can you adjust the kerning?
__Downloaded card image__
![screenshot00126](https://cloud.githubusercontent.com/assets/2443519/7316568/fa550b46-ea6f-11e4-9192-5dc8dc52b8ec.png)
__CardBuilder__
![screenshot00127](https://cloud.githubusercontent.com/assets/2443519/7316571/feeaf0e4-ea6f-11e4-96c2-e608df0ac31c.png)

**Comment by ShawnieBoy** [comment]
I'm afraid not - the kerning function for attributed strings isn't currently working. :cry:

**Comment by lodici** [comment]
I meant to ask, why attributed string? This is the first time I have ever come across them.

**Comment by ShawnieBoy** [comment]
Me too.
Actually I only need them for the text box... They allow you to do more fiddly things with text strings. I'm mainly using them for paragraph spacing/layout and in-text image placement.

**Comment by ShawnieBoy** [comment]
I'll have a look at it now - just finished this: 
![new render](https://cloud.githubusercontent.com/assets/2363180/7316915/1baad0b6-ea73-11e4-81ce-f95f364981e7.png)

![new render 3](https://cloud.githubusercontent.com/assets/2363180/7316922/20b2d338-ea73-11e4-8a18-b97ceec7794b.png)

Default images done

**Comment by lodici** [comment]
Awesome!

**Comment by ShawnieBoy** [comment]
ty - not done a hybrid one yet

**Comment by ShawnieBoy** [comment]
Well, good news is that I've got the kerning on - bad news is that it looks like it's a font issue

**Comment by ShawnieBoy** [comment]
Putting Kerning on an attributed string is bugged, but putting it directly on a font isn't :grinning: 

It may be that the glyph boundaries are a bit off - I'll see if I can dust off some font software and have a look.

**Comment by ShawnieBoy** [comment]
Actually the kerning for the font is fairly good - the issue with 'er' looks like the font size. I'll up it a touch and see if that makes things better.

**Comment by ShawnieBoy** [comment]
![afterlife](https://cloud.githubusercontent.com/assets/2363180/7317523/ae90747a-ea79-11e4-8b98-b8ab8204c7b7.png)

Looks like that's sorted it

**Comment by lodici** [comment]
That is certainly better (the scrunched "er" was horrible). Good job.
