### ISSUE TITLE
Subtype ordering

### ISSUE THREAD

**Issue by ShawnieBoy** [lodici/magarena-cardbuilder#24]
Somewhere inside Magarena the creature subtypes are being put into alphabetical order. This can be seen in the Card Explorer, eg: Tobias Andrion

Script: Human, Advisor
CardBuilder + Card Explorer: Advisor, Human

**Comment by lodici** [comment]
I would imagine it is using the order as defined in ``MagicSubType``. Looks like you might need to update MagicCardDefinition to include a field which stores the subtypes in the exact order as defined in the script for display purposes.

**Comment by ShawnieBoy** [comment]
fixed with eafe65270c920816cd07d33d0cde9724cb4d26e8
