### ISSUE TITLE
Thoughts on CardBuilder second-phase integration specifics.

### ISSUE THREAD

**Issue by lodici** [lodici/magarena-cardbuilder#26]
The second "``MagicCard``" phase is to use CardBuilder to dynamically generate the images used during a game including displaying adjustments to card properties through activated abilities and so forth. Will build upon the work completed in phase one which should have already been integerated into Magarena and proven itself stable and robust.

**Comment by melvinzhang** [comment]
migrated to https://github.com/magarena/magarena/issues/623
