### ISSUE TITLE
Reminder Text

### ISSUE THREAD

**Issue by ShawnieBoy** [lodici/magarena-cardbuilder#33]
With cards appearing in-game in the latest rounds of edits, I've personally found myself querying some of the newer ability keywords.

Thankfully there is a glossary to help! (Never used it before)

But this does raise the question about reminder text for non-evergreen keywords for cardBuilder.

Do we keep the text as is, (no reminder text) and use the glossary for clarification? (No work needed besides keeping the glossary up to date).

Or do we implement reminder text for all non-evergreen keywords? (Will require re-parsing all cards, in addition to work on cardBuilder)

Or something else?

**Comment by melvinzhang** [comment]
The reminder text adds a lot of words to the text box. How about popping up a tool tip with reminder text if the user's mouse stay on the card for a certain time?

**Comment by ShawnieBoy** [comment]
@melvinzhang We already have a larger image for popup, but I like the idea of the information coming from somewhere else. Some text is small enough already, without cramming in more!

If the pop-up image was more of a toggle, that could work, as then similar to the ability icons on the side, there could be reminder-text hint-boxes you could cursor over, or click

**Comment by melvinzhang** [comment]
@ShawnieBoy Sorry for the confusion, I was referring to mouse over of the larger image, not the one on the battlefield/hand. If the user mouse over the larger image for a certain time or provide a tool tips icon like one of the ability icon which you can mouse over for the reminder text.
