### ISSUE TITLE
Land Colors + Mana-Activations error

### ISSUE THREAD

**Issue by ShawnieBoy** [lodici/magarena-cardbuilder#34]
Somewhere along the line it looks like something strange has occurred with `.getManaActivations().size()`
At the moment I'm having it return '0' for all lands, and so all lands (except those with basic land-types, which are checked by subtype) are returning colourless.

??

**Comment by ShawnieBoy** [comment]
Ok, looks like this only occurs if the game isn't run in dev-mode. The cardDefinitions don't seem to have the manaActivations created for them otherwise.

**Comment by ShawnieBoy** [comment]
Without increasing the loading times, I could instead look for `Add {mana} to your mana pool` in the oracle text, but that could cause problems when it comes to cards on the battlefield.

**Comment by melvinzhang** [comment]
Parsing of groovy and abilities are the slow steps in card loading, they are delayed until MagicCard is created. dev-mode loads all of them at start to detect any issues, but as you've noticed it is slow due to all the groovy/ability loading.
