### ISSUE TITLE
Obtaining values from Abilities

### ISSUE THREAD

**Issue by ShawnieBoy** [lodici/magarena-cardbuilder#35]
Hopefully @melvinzhang can help with this.

I'm trying to pull the int values from Loyalty. Is there currenly any way of doing this, or would this need new methods for the abilities?

Essentially the cardbuilder will need to know what the starting loyalty and the costs of all planeswalker abilities on Planeswalker cards. Likewise for the level boundaries for leveller cards. The activated abilities and level boundaries are fine, as they can be pulled from the Oracle text. However the oracle has no reference for the starting loyalty value for Planeswalkers.

**Comment by melvinzhang** [comment]
There is no way of extracting the starting loyalty programatically. The loyalty keyword in ability is translated into a MagicComesIntoPlayWithCounterTrigger(MagicCounterType.Loyalty,n) and is stored as a MagicWhenComesIntoPlayTrigger in MagicCardDefinition.

One solution is include an additional int in MagicCardDefinition which is the loyalty, but it seems a bit wasteful as only planeswalker would have a non-zero value of this properly. Another solution is to add it to the oracle text.

**Comment by ShawnieBoy** [comment]
Starting loyalty used to be defined at CardDefinition level, and then the trigger created from that instead of an ability. Wondering if it could be worth doing that?
Adding it into the oracle is a possibility, but would need some editing of the Scriptbuilder.

**Comment by melvinzhang** [comment]
> Starting loyalty used to be defined at CardDefinition level, and then the trigger created from that instead of an ability.

I don't recall that being the case, can you point to a commit with this implementation. Garruk, Primal Hunter is the first planeswalker implemented, and at first it has the ability "enters with charge 3"

**Comment by melvinzhang** [comment]
https://github.com/magarena/magarena/commit/306366434f02cec3b2cc3b3b98aaacc82f95c870 adds a startingLoyalty field to MagicCardDefinition. Retrieve with getStartingLoyalty()

**Comment by ShawnieBoy** [comment]
Maybe I'm getting confused with Equip, but I was sure Loyalty was represented as just 'loyalty=<int>" as a card property.

**Comment by melvinzhang** [comment]
Perhaps you were thinking of the format shown on gatherer.

**Comment by ShawnieBoy** [comment]
Ahh, cool thanks - Probably. Weird how the brain works sometimes, hehe.

**Comment by ShawnieBoy** [comment]
Although, while the card is a card, it's going to have a starting loyalty of 0

**Comment by melvinzhang** [comment]
Oh, good catch. Ability are only parsed when used in the game. Fixed in https://github.com/magarena/magarena/commit/2c7e81accede2c1c9039b56d0d2a746bb79c9d3e by use loyalty property in card script.

**Comment by ShawnieBoy** [comment]
Thanks :grinning:
