### ISSUE TITLE
Transfer repo

### ISSUE THREAD

**Issue by lodici** [lodici/magarena-cardbuilder#36]
@ShawnieBoy can I transfer ownership of ```magarena-cardbuilder``` to you? I want to test Travis CI with a fork of the main repo but you can only have one fork of it as far as I can see.

**Comment by ShawnieBoy** [comment]
Yes, that should be fine - I won't have much access to repositories etc at the moment as I've fairly limited pc and internet access. As long as I don't need to do anything - transfer away :)
