### ISSUE TITLE
migrate issues that are unresolved to main repo

### ISSUE THREAD

**Issue by melvinzhang** [lodici/magarena-cardbuilder#37]
As card builder is not integrated with the main repo, issues should be moved to the main repo.

**Comment by melvinzhang** [comment]
@ShawnieBoy there may be some relevant issues here, if so please help to move them to the main repo. Thanks!

**Comment by ShawnieBoy** [comment]
Looks like you've beat me to it :grinning: I didn't think there were any relevant ones left after some got lost during transfer the first time.

**Comment by melvinzhang** [comment]
@ShawnieBoy I only moved the one I could understand, about using card builder for in-game images. The other 9 I left alone as I could not tell if they are still relevant or now. Could you either close them here or move them to the main repo.

**Comment by ShawnieBoy** [comment]
Oh, my bad - I just saw that magarena/cardbuilder had dissapeared, didn't realise this was on lodici's repository.

**Comment by ShawnieBoy** [comment]
Most of the issues have either been resolved or re-raised/covered in the main repo.

This can be properly closed now
