### ISSUE TITLE
Enable Non-int power/toughness

### ISSUE THREAD

**Issue by ShawnieBoy** [lodici/magarena-cardbuilder#5]
_From @ShawnieBoy on April 20, 2015 3:36_

A question for you @melvinzhang in a more appropriate place.

How does MagicCardDefinition deal with non-integer power/toughness as in `*/*` or` 2+*/2+*` etc?

_Copied from original issue: magarena/magarenaCardBuilder#5_

**Comment by ShawnieBoy** [comment]
_From @melvinzhang on April 20, 2015 3:47_

It treats anything with a * in it as 0.

**Comment by ShawnieBoy** [comment]
That may be a bit tricky from a cardBuilder perspective, as it will be trying to get it's 'out of game' state.

**Comment by ShawnieBoy** [comment]
I guess it would have to go back to the card script itself

**Comment by ShawnieBoy** [comment]
_From @melvinzhang on April 20, 2015 4:0_

Anything with * is accompanied by a MagicCDA. The card builder should show the current numerical value, obtained from MagicCard.getPower() and MagicCard.getToughness()

**Comment by ShawnieBoy** [comment]
Which is fine in a game situation, but in the Card Explorer/Deck editor, the value will show '0' instead.

**Comment by ShawnieBoy** [comment]
added powerToughnessText to MagicCardDefinition and CardProperty to allow rendering of non-int power/toughness. This string could be split for displaying correctly in the Card Explorer as well @lodici

**Comment by lodici** [comment]
> This string could be split for displaying correctly in the Card Explorer as well @lodici

take a look at ``case 3`` and ``case 4`` in [``CardTableModel.getValueAt()``](https://github.com/lodici/magarena-cardbuilder/blob/master/src/magic/ui/cardtable/CardTableModel.java#L228).

**Comment by ShawnieBoy** [comment]
:+1:

**Comment by ShawnieBoy** [comment]
A similar strategy could be used for the subtype issue as well #15

**Comment by ShawnieBoy** [comment]
I think this can be pushed to the main repository, working fine :grinning:

**Comment by ShawnieBoy** [comment]
Although the sort isn't grouping them together - looks good.
![powertoughness](https://cloud.githubusercontent.com/assets/2363180/7442549/f816674a-f10d-11e4-97c3-c200c3ad1296.png)

**Comment by ShawnieBoy** [comment]
Also a shame that the mPlantin font doesn't have the glyph for Black Star, but I may be able to fix that.

**Comment by ShawnieBoy** [comment]
My bad, mPlantin has is replaced into Asterix, but Beleren doesn't
