### ISSUE TITLE
Hybrid Colour card frames

### ISSUE THREAD

**Issue by ShawnieBoy** [lodici/magarena-cardbuilder#7]
_From @ShawnieBoy on April 21, 2015 18:36_

Enable horizontal blend of hybrid multicolor cards.

_Copied from original issue: magarena/magarenaCardBuilder#7_

**Comment by ShawnieBoy** [comment]
Also applies to the 'piping' of dual-coloured mulitcolored cards and land

**Comment by lodici** [comment]
Also while your at it I noticed some rather attractive foil overlays on the Magic Editor site! :smile:

**Comment by ShawnieBoy** [comment]
:stuck_out_tongue_closed_eyes:

**Comment by ShawnieBoy** [comment]
Ok, this might explain why I'm having trouble - Where are the images being referenced from? Just to test, I removed the artifact frame from the resources folder and it's still appearing in renders

**Comment by ShawnieBoy** [comment]
I can't work out why this is consistently rendering blank (ie.black) - I've pushed up what I have so far and will have a look at it again later on.

**Comment by lodici** [comment]
Sorry, not sure if you want this closed. This also fixed the black border corner transparency as well.
![screenshot00125](https://cloud.githubusercontent.com/assets/2443519/7299266/c559f30a-e9cc-11e4-8e4c-6d89a4474114.png)

**Comment by ShawnieBoy** [comment]
Ahh, cool -

**Comment by ShawnieBoy** [comment]
Hmm, should be Blue -> Black as well...

**Comment by ShawnieBoy** [comment]
OK, got hybrids, Multi and 'colorless' multi (artifacts) sorted, just need to get half of the color pairings in the correct order:
![hybrid](https://cloud.githubusercontent.com/assets/2363180/7313227/6e87bb4c-ea4f-11e4-8624-d437fdfdbdb5.png)
![multi](https://cloud.githubusercontent.com/assets/2363180/7313228/72a54ce4-ea4f-11e4-8445-528679dff87a.png)
![hybrid artifact](https://cloud.githubusercontent.com/assets/2363180/7313233/7690bc08-ea4f-11e4-8a2a-16f08579e8a9.png)
